# Generated by Django 3.2.3 on 2021-05-24 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_comment_moviecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviecomment',
            old_name='content',
            new_name='comment',
        ),
    ]
