# Generated by Django 3.2.3 on 2021-05-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_content_moviecomment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecomment',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
