# Generated by Django 3.2.3 on 2021-05-24 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20210524_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='movie_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rank',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
