# Generated by Django 3.2.3 on 2021-05-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20210524_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='review',
            new_name='post',
        ),
    ]
